INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(18, 'Moonika', 'Kuusk');
INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(20, 'Zelda', 'Colin');
INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(17, 'Mia', 'Corn');