INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(18, 'Moonika', 'Kuusk');
INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(20, 'Zelda', 'Colin');
INSERT INTO PERSON_ENTITIES (AGE, NAME,SURNAME)
VALUES(17, 'Mia', 'Corn');

INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Blanket', 150);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Billow', 60);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Towel', 25);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES ('Mattress', 100);


